//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BM.GestaoProblema.Infra.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BM.GestaoProblema.Infra.CrossCutting.Resources.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O analista não foi encontrado.
        /// </summary>
        public static string AnalistaNaoEncontrado {
            get {
                return ResourceManager.GetString("AnalistaNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do analista está inválido.
        /// </summary>
        public static string AnalistaNomeInvalido {
            get {
                return ResourceManager.GetString("AnalistaNomeInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O time de suporte do analista está inválido.
        /// </summary>
        public static string AnalistaTimeSuporteInvalido {
            get {
                return ResourceManager.GetString("AnalistaTimeSuporteInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O chamado foi aberto às {0} para o sistema {1}.
        /// </summary>
        public static string ChamadoAberto {
            get {
                return ResourceManager.GetString("ChamadoAberto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O analista em atendimento está inválido.
        /// </summary>
        public static string ChamadoAnalistaEmAtendimentoInvalido {
            get {
                return ResourceManager.GetString("ChamadoAnalistaEmAtendimentoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O chamado foi colocado em atendimento às {0} por {1}.
        /// </summary>
        public static string ChamadoEmAtendimento {
            get {
                return ResourceManager.GetString("ChamadoEmAtendimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O chamado foi finalizado às {0} por {1}.
        /// </summary>
        public static string ChamadoFinalizado {
            get {
                return ResourceManager.GetString("ChamadoFinalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O chamado já foi finalizado ou está em atendimento por um analista.
        /// </summary>
        public static string ChamadoJaFinalizadoOuEmAtendimentoPorUmAnalista {
            get {
                return ResourceManager.GetString("ChamadoJaFinalizadoOuEmAtendimentoPorUmAnalista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O chamado não foi atendindo.
        /// </summary>
        public static string ChamadoNaoAtendido {
            get {
                return ResourceManager.GetString("ChamadoNaoAtendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O chamado não foi encontrado.
        /// </summary>
        public static string ChamadoNaoEncontrado {
            get {
                return ResourceManager.GetString("ChamadoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi configurada um prazo de solução para esta prioridade.
        /// </summary>
        public static string ChamadoPrazoSolucaoPrioridadeNaoConfigurada {
            get {
                return ResourceManager.GetString("ChamadoPrazoSolucaoPrioridadeNaoConfigurada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sistema do chamado está inválido.
        /// </summary>
        public static string ChamadoSistemaInvalido {
            get {
                return ResourceManager.GetString("ChamadoSistemaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sistema não foi encontrado.
        /// </summary>
        public static string SistemaNaoEncontrado {
            get {
                return ResourceManager.GetString("SistemaNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do sistema está inválido.
        /// </summary>
        public static string SistemaNomeInvalido {
            get {
                return ResourceManager.GetString("SistemaNomeInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O time de suporte do sistema está inválido.
        /// </summary>
        public static string SistemaTimeSuporteInvalido {
            get {
                return ResourceManager.GetString("SistemaTimeSuporteInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do time de suporte está inválido.
        /// </summary>
        public static string TimeSuporteDescricaoInvalido {
            get {
                return ResourceManager.GetString("TimeSuporteDescricaoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do time de suporte está inválido.
        /// </summary>
        public static string TimeSuporteNomeInvalido {
            get {
                return ResourceManager.GetString("TimeSuporteNomeInvalido", resourceCulture);
            }
        }
    }
}
